// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="syfala_syfala,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=8.138000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.312000,HLS_SYN_LAT=23,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=585,HLS_SYN_LUT=1068,HLS_VERSION=2024_2}" *)

module syfala (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        audio_out
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] audio_out;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] syfala_ap_int_8_DSP_iVec0_1;
reg   [31:0] syfala_ap_int_8_DSP_fRec0_1;
wire   [4:0] mask_table_address0;
wire   [22:0] mask_table_q0;
wire   [31:0] grp_fu_115_p2;
reg   [31:0] reg_129;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state15;
wire   [31:0] grp_fu_121_p1;
reg   [31:0] iVec01_reg_436;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln123_fu_166_p2;
reg   [0:0] icmp_ln123_reg_444;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln123_1_fu_172_p2;
reg   [0:0] icmp_ln123_1_reg_449;
wire   [0:0] grp_fu_124_p2;
reg   [0:0] tmp_2_reg_454;
wire   [31:0] fTemp0_fu_187_p3;
reg   [31:0] fTemp0_reg_459;
wire    ap_CS_fsm_state16;
reg   [0:0] xs_sign_reg_465;
reg   [7:0] xs_exp_reg_474;
wire   [22:0] xs_sig_fu_215_p1;
reg   [22:0] xs_sig_reg_482;
wire   [30:0] trunc_ln313_fu_234_p1;
reg   [30:0] trunc_ln313_reg_493;
reg   [0:0] xs_sign_1_reg_498;
wire    ap_CS_fsm_state17;
reg   [7:0] xs_exp_1_reg_503;
wire   [22:0] xs_sig_3_fu_287_p2;
reg   [22:0] xs_sig_3_reg_508;
wire   [0:0] icmp_ln19_fu_293_p2;
reg   [0:0] icmp_ln19_reg_513;
wire   [31:0] retval_0_i_fu_396_p11;
reg   [31:0] retval_0_i_reg_518;
wire    ap_CS_fsm_state18;
wire   [63:0] zext_ln32_fu_229_p1;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state10;
reg    mask_table_ce0_local;
reg   [31:0] grp_fu_115_p0;
reg   [31:0] grp_fu_115_p1;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state19;
wire   [31:0] grp_fu_121_p0;
wire   [31:0] bitcast_ln123_fu_148_p1;
wire   [7:0] tmp_1_fu_152_p4;
wire   [22:0] trunc_ln123_fu_162_p1;
wire   [0:0] or_ln123_fu_178_p2;
wire   [0:0] and_ln123_fu_182_p2;
wire   [31:0] data_fu_195_p1;
wire   [4:0] index_fu_219_p4;
wire   [31:0] zext_ln28_fu_238_p1;
wire   [31:0] t_fu_242_p3;
wire   [31:0] data_1_fu_249_p2;
wire   [22:0] xs_sig_1_fu_271_p1;
wire   [22:0] xs_sig_2_fu_275_p3;
wire   [22:0] xor_ln39_fu_281_p2;
wire   [31:0] t_3_fu_308_p3;
wire   [0:0] xs_sign_2_fu_319_p2;
wire   [7:0] xs_exp_2_fu_323_p3;
wire   [31:0] t_4_fu_328_p4;
wire   [0:0] icmp_ln18_fu_298_p2;
wire   [0:0] icmp_ln24_fu_303_p2;
wire   [0:0] xor_ln18_fu_341_p2;
wire   [0:0] or_ln24_fu_353_p2;
wire   [0:0] icmp_ln19_1_fu_365_p2;
wire   [0:0] or_ln19_fu_370_p2;
wire   [0:0] and_ln19_fu_375_p2;
wire   [0:0] and_ln24_fu_347_p2;
wire   [0:0] xor_ln24_fu_359_p2;
wire   [0:0] and_ln19_1_fu_380_p2;
wire   [31:0] retval_0_i_fu_396_p4;
wire   [31:0] retval_0_i_fu_396_p8;
wire   [31:0] retval_0_i_fu_396_p9;
wire   [2:0] retval_0_i_fu_396_p10;
reg   [1:0] grp_fu_115_opcode;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire  signed [2:0] retval_0_i_fu_396_p1;
wire   [2:0] retval_0_i_fu_396_p3;
wire   [2:0] retval_0_i_fu_396_p5;
wire   [2:0] retval_0_i_fu_396_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 syfala_ap_int_8_DSP_iVec0_1 = 1'd0;
#0 syfala_ap_int_8_DSP_fRec0_1 = 32'd0;
end

syfala_mask_table_ROM_AUTO_1R #(
    .DataWidth( 23 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mask_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mask_table_address0),
    .ce0(mask_table_ce0_local),
    .q0(mask_table_q0)
);

syfala_faddfsub_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_6_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_115_p0),
    .din1(grp_fu_115_p1),
    .opcode(grp_fu_115_opcode),
    .ce(1'b1),
    .dout(grp_fu_115_p2)
);

syfala_sitofp_32ns_32_7_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_7_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_121_p0),
    .ce(1'b1),
    .dout(grp_fu_121_p1)
);

syfala_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_129),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd1),
    .dout(grp_fu_124_p2)
);

(* dissolve_hierarchy = "yes" *) syfala_sparsemux_9_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_1_U4(
    .din0(fTemp0_reg_459),
    .din1(retval_0_i_fu_396_p4),
    .din2(32'd3212836864),
    .din3(retval_0_i_fu_396_p8),
    .def(retval_0_i_fu_396_p9),
    .sel(retval_0_i_fu_396_p10),
    .dout(retval_0_i_fu_396_p11)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fTemp0_reg_459 <= fTemp0_fu_187_p3;
        trunc_ln313_reg_493 <= trunc_ln313_fu_234_p1;
        xs_exp_reg_474 <= {{data_fu_195_p1[30:23]}};
        xs_sig_reg_482 <= xs_sig_fu_215_p1;
        xs_sign_reg_465 <= data_fu_195_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        iVec01_reg_436 <= grp_fu_121_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        icmp_ln123_1_reg_449 <= icmp_ln123_1_fu_172_p2;
        icmp_ln123_reg_444 <= icmp_ln123_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        icmp_ln19_reg_513 <= icmp_ln19_fu_293_p2;
        xs_exp_1_reg_503 <= {{data_1_fu_249_p2[30:23]}};
        xs_sig_3_reg_508 <= xs_sig_3_fu_287_p2;
        xs_sign_1_reg_498 <= data_1_fu_249_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        reg_129 <= grp_fu_115_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        retval_0_i_reg_518 <= retval_0_i_fu_396_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        syfala_ap_int_8_DSP_fRec0_1 <= grp_fu_115_p2;
        syfala_ap_int_8_DSP_iVec0_1 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_2_reg_454 <= grp_fu_124_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_115_opcode = 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_115_opcode = 2'd0;
    end else begin
        grp_fu_115_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_115_p0 = fTemp0_reg_459;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_115_p0 = syfala_ap_int_8_DSP_fRec0_1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_115_p0 = 32'd1065353216;
    end else begin
        grp_fu_115_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_115_p1 = retval_0_i_reg_518;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_115_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_115_p1 = iVec01_reg_436;
    end else begin
        grp_fu_115_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        mask_table_ce0_local = 1'b1;
    end else begin
        mask_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln123_fu_182_p2 = (tmp_2_reg_454 & or_ln123_fu_178_p2);

assign and_ln19_1_fu_380_p2 = (icmp_ln18_fu_298_p2 & and_ln19_fu_375_p2);

assign and_ln19_fu_375_p2 = (xs_sign_reg_465 & or_ln19_fu_370_p2);

assign and_ln24_fu_347_p2 = (xor_ln18_fu_341_p2 & icmp_ln24_fu_303_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign bitcast_ln123_fu_148_p1 = reg_129;

assign data_1_fu_249_p2 = (zext_ln28_fu_238_p1 + t_fu_242_p3);

assign data_fu_195_p1 = fTemp0_fu_187_p3;

assign fTemp0_fu_187_p3 = ((and_ln123_fu_182_p2[0:0] == 1'b1) ? reg_129 : 32'd0);

assign grp_fu_121_p0 = syfala_ap_int_8_DSP_iVec0_1;

assign icmp_ln123_1_fu_172_p2 = ((trunc_ln123_fu_162_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_166_p2 = ((tmp_1_fu_152_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_298_p2 = ((xs_exp_reg_474 < 8'd127) ? 1'b1 : 1'b0);

assign icmp_ln19_1_fu_365_p2 = ((xs_exp_reg_474 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_293_p2 = ((xs_sig_reg_482 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_303_p2 = ((xs_exp_reg_474 > 8'd150) ? 1'b1 : 1'b0);

assign index_fu_219_p4 = {{data_fu_195_p1[27:23]}};

assign mask_table_address0 = zext_ln32_fu_229_p1;

assign or_ln123_fu_178_p2 = (icmp_ln123_reg_444 | icmp_ln123_1_reg_449);

assign or_ln19_fu_370_p2 = (icmp_ln19_reg_513 | icmp_ln19_1_fu_365_p2);

assign or_ln24_fu_353_p2 = (icmp_ln24_fu_303_p2 | icmp_ln18_fu_298_p2);

assign retval_0_i_fu_396_p10 = {{{and_ln24_fu_347_p2}, {xor_ln24_fu_359_p2}}, {and_ln19_1_fu_380_p2}};

assign retval_0_i_fu_396_p4 = t_4_fu_328_p4;

assign retval_0_i_fu_396_p8 = t_3_fu_308_p3;

assign retval_0_i_fu_396_p9 = 'bx;

assign t_3_fu_308_p3 = {{xs_sign_reg_465}, {31'd0}};

assign t_4_fu_328_p4 = {{{xs_sign_2_fu_319_p2}, {xs_exp_2_fu_323_p3}}, {xs_sig_3_reg_508}};

assign t_fu_242_p3 = {{1'd1}, {trunc_ln313_reg_493}};

assign tmp_1_fu_152_p4 = {{bitcast_ln123_fu_148_p1[30:23]}};

assign trunc_ln123_fu_162_p1 = bitcast_ln123_fu_148_p1[22:0];

assign trunc_ln313_fu_234_p1 = data_fu_195_p1[30:0];

assign xor_ln18_fu_341_p2 = (icmp_ln18_fu_298_p2 ^ 1'd1);

assign xor_ln24_fu_359_p2 = (or_ln24_fu_353_p2 ^ 1'd1);

assign xor_ln39_fu_281_p2 = (mask_table_q0 ^ 23'd8388607);

assign xs_exp_2_fu_323_p3 = ((xs_sign_reg_465[0:0] == 1'b1) ? xs_exp_1_reg_503 : xs_exp_reg_474);

assign xs_sig_1_fu_271_p1 = data_1_fu_249_p2[22:0];

assign xs_sig_2_fu_275_p3 = ((xs_sign_reg_465[0:0] == 1'b1) ? xs_sig_1_fu_271_p1 : xs_sig_reg_482);

assign xs_sig_3_fu_287_p2 = (xs_sig_2_fu_275_p3 & xor_ln39_fu_281_p2);

assign xs_sig_fu_215_p1 = data_fu_195_p1[22:0];

assign xs_sign_2_fu_319_p2 = (xs_sign_reg_465 & xs_sign_1_reg_498);

assign zext_ln28_fu_238_p1 = mask_table_q0;

assign zext_ln32_fu_229_p1 = index_fu_219_p4;

endmodule //syfala
